variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "name" {
  description = "Base name for resources"
  type        = string
  default     = "fastapi-uv-demo"
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t3.micro"
}

variable "ssh_public_key" {
  description = "Optional SSH public key to create a key pair (empty to skip)"
  type        = string
  default     = ""
}

variable "ssh_cidr" {
  description = "Optional CIDR allowed for SSH (e.g., 203.0.113.0/32). Empty disables SSH."
  type        = string
  default     = ""
}

variable "ssh_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "github_repo_url" {
  description = "GitHub repository to clone (https://github.com/org/repo.git)"
  type        = string
  default     = "https://github.com/YOUR_ORG/YOUR_REPO.git"
}
